
<div class="columns text-center">

    <h1> Register </h1>

    <div class="form-sign-in card text-left">
        <form method="post">

            <div class="form-row">
                <label>Username
                    <input class="input" type="text" name="username" placeholder="username" />
                </label>
            </div>

            <div class="form-row">
                <label>Email
                    <input class="input" type="text" name="email" placeholder="email" />
                </label>
            </div>

            <div class="form-row">
                <label>Password
                    <input class="input" type="password" name="password" placeholder="password" />
                </label>
            </div>

            <div class="form-row">
                <label>Confirm Password
                    <input class="input" type="password" name="password" placeholder="password" />
                </label>
            </div>

            <div class="form-row">
                <div class="to-table">
                    <div class="">
                        <a href="/signin" class="button">Sign In</a>
                    </div>
                    <div class="text-right">
                        <button class="button">Register</button>
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="info text-center">info text</div>
            </div>

        </form>
    </div>

</div>
