
<div class="columns text-center">

    <h1> Login </h1>

    <div class="notice">Demo login is <strong>guest</strong>, password <strong>12345</strong></div>

    <div class="form-sign-in card text-left">
        <form method="post">

            <div class="form-row">
                <label>Username
                    <input class="input" type="text" name="username" placeholder="username" />
                </label>
            </div>

            <div class="form-row">
                <label>Password
                    <input class="input" type="password" name="password" placeholder="password" />
                </label>
            </div>

            <div class="form-row">
                <div class="to-table">
                    <div class="">
                        <a href="/register" class="button">Register</a>
                    </div>
                    <div class=" text-right">
                        <button class="button">Sign In</button>
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="info text-center">info text</div>
            </div>

        </form>
    </div>

</div>
